### ISSUE TITLE
Not an issue, just a question...

### ISSUE THREAD

**Issue by Shadowtrance** [tebl/C64-JoyKEY#1]
Just got some of these boards made to use with my c64 and such, nice little creation. :)

Oddly enough, amongst all my parts I have zero 270 ohm resistors anywhere, 220 and 360 are probably the closest I have on hand. haha

Is there any other value I can safely use in their place? or can I just omit them totally until I get some?

Also got your Pi1541 hat made too which works a treat. :)

**Comment by tebl** [comment]
They are just there in order to somewhat protect the computer in case the
polarity haven't been set up to match, a 220 resistor would probably work
just the same. A wire would also work though it would offer no "failsafe".

tor. 29. jul. 2021, 14:41 skrev Shadowtrance ***@***.***>:
