### ISSUE TITLE
Underglow LED without arduino.

### ISSUE THREAD

**Issue by Retrofletch** [tebl/C64-JoyKEY#2]
i noticed that because the arduino controls the underglow led's there will be no keycap light when not using the arduino.

I figured out that its basicly just sending vcc to the base pin of the transistor thru a 1k resistor so linking any VCC to R13 makes it work, is there any better way of doing this? or any technical reason why i should not solve it that way?

( i have the version before you added the 3 push buttons at bottom left )

thanks /Fletch

**Comment by tebl** [comment]
I think it depends on whether the Arduino is installed at all, but I think
the easiest is probably removing Q1 entirely, then adding a short wire
between pins 1 and 3 (that way you can still remove KEY-LED jumper to
disable it when needed). If the LEDs are too bright, use a resistor instead
of the wire.

lør. 16. jul. 2022, 12:17 skrev RetroFletch ***@***.***>:

**Comment by Retrofletch** [comment]
Will try that on the next build, thanks
